/**
 * Email Notification Utility
 */

import nodemailer from 'nodemailer';
import { promises as fs } from 'fs';
import path from 'path';
import yaml from 'yaml';

const ROOT_DIR = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');

export async function sendNotification({ to, subject, reportUrl, propertyName, summary }) {
  // Load settings
  let settings;
  try {
    const settingsPath = path.join(ROOT_DIR, 'config/settings.yaml');
    settings = yaml.parse(await fs.readFile(settingsPath, 'utf8'));
  } catch (e) {
    console.log('Could not load settings:', e.message);
    return false;
  }

  const emailConfig = settings.notifications?.email;
  if (!emailConfig?.enabled) {
    console.log('Email notifications disabled in settings');
    return false;
  }

  // Check if SMTP credentials are configured
  if (!emailConfig.smtp?.user || !emailConfig.smtp?.password) {
    console.log('SMTP credentials not configured in settings.yaml');
    console.log('To enable email notifications, add your Gmail address and App Password to:');
    console.log('  /Users/robroyhobbs/content-automation/config/settings.yaml');
    return false;
  }

  const transporter = nodemailer.createTransport({
    host: emailConfig.smtp.host || 'smtp.gmail.com',
    port: emailConfig.smtp.port || 587,
    secure: false,
    auth: {
      user: emailConfig.smtp.user,
      pass: emailConfig.smtp.password
    }
  });

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        h2 { color: #4F46E5; }
        .cta { display: inline-block; background: #4F46E5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin: 20px 0; }
        .metrics { background: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .metric { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
        .metric:last-child { border-bottom: none; }
        .footer { color: #6b7280; font-size: 12px; margin-top: 30px; }
      </style>
    </head>
    <body>
      <div class="container">
        <h2>${propertyName} Weekly Analytics Report</h2>
        <p>Your weekly analytics report is ready for review before the Thursday all-hands meeting.</p>

        <a href="${reportUrl}" class="cta">View Full Report</a>

        <div class="metrics">
          <h3>Quick Summary</h3>
          <div class="metric">
            <span>Active Users</span>
            <strong>${summary.activeUsers} (${summary.activeUsersChange})</strong>
          </div>
          <div class="metric">
            <span>New Users</span>
            <strong>${summary.newUsers} (${summary.newUsersChange})</strong>
          </div>
          <div class="metric">
            <span>Engagement Rate</span>
            <strong>${summary.engagementRate}</strong>
          </div>
        </div>

        <p><strong>Report URL:</strong><br>
        <a href="${reportUrl}">${reportUrl}</a></p>

        <div class="footer">
          Generated by Content Automation Hub<br>
          ${new Date().toISOString()}
        </div>
      </div>
    </body>
    </html>
  `;

  try {
    await transporter.sendMail({
      from: emailConfig.from || emailConfig.smtp.user,
      to: to || emailConfig.to,
      subject,
      html
    });
    console.log('✅ Email notification sent to:', to || emailConfig.to);
    return true;
  } catch (error) {
    console.error('❌ Email failed:', error.message);
    return false;
  }
}

export default { sendNotification };
